### ISSUE TITLE
Transcripts page Mobile Issues

### ISSUE THREAD

**Issue by wesbos** [syntaxfm/website#1258]
1. it has horz scroll 
2. I think the speakers name could be rotated sideways to make more room for the actual transcript

**Comment by MarekKabala1** [comment]
Is not just issue that is overflowing "horizontal scroll". When i scroll because you have that issue  im unable to see full transcript, black background on the text. Android 13, Chrome version 119.0.6045.163. And on the desktop you have a sticky position for the h4 Transcript header Scott name is to long and overflowing on the left you can se the first letter from his name. I was checking on the Show 697.

**Comment by wesbos** [comment]
@themisterholliday thanks! That was exactly the fix. Also added a new layout for mobile so transcripts are easier to read
<img width="597" alt="Screenshot 2024-02-20 at 5 38 36 PM" src="https://github.com/syntaxfm/website/assets/176013/b1a2ac42-3d12-4f2e-af3d-177e6d62bf3e">
