### ISSUE TITLE
Theme defaulting to light on refresh

### ISSUE THREAD

**Issue by stolinski** [syntaxfm/website#1582]
Not sure if this is widespread but it's happening for me. I'm sure it's related to the  server side loading of themes work I did last week. Investigating.

**Comment by stolinski** [comment]
seems to work fine locally. That indicates it might be a cookie issue since themes are stored as a cookie.

**Comment by stolinski** [comment]
AH! Caching. No wonder it's not happening on dev. Since the theme is coming from the server, the server response is cached from http caching, it's not getting server on refresh.

**Comment by stolinski** [comment]
It's actually not defaulting to light, but to system and is not a caching issue. Turned off caching and it still has the same issue. Probably a cookie options issue as originally expected.

**Comment by wesbos** [comment]
This was happening a while back. It seems like whatever the first render renders as, its cached? It happened with me once where I was getting Ben's custom theme on the production website. 

We are server rendering with the cookie right? The first render would take that user's cookie and then cache that page until we revlidate it. 

Kind of a common issue - do we want to cache the page for everyone? Or deliver a customized experience?

I think the solution is to use the variants as some sort of cache-key? Not sure how to approach that since it's using CDN caching. Maybe something in middleware?

**Comment by stolinski** [comment]
TBH I don't think it's caching, but it could be. The cookie exists in the application, but is not getting set properly on initial load. My guess is that the prod server isn't getting access to the cookie on initial load so it's defaulting to system.

**Comment by stolinski** [comment]
SPOILER. It was caching.

**Comment by stolinski** [comment]
Ok this is fixed.

**Comment by abhibeckert** [comment]
Quick tip - rather than doing this server side, do it client side:

```
<head>
  <script>
    const theme = localStorage.getItem('theme');
    if (theme) {
      document.body.classList.add(theme);
    }
  </script>
</head>
```

Since it’s in the head, and doesn’t do any network requests or wait for events, the page can’t render with the old theme first.
