### ISSUE TITLE
RSS issues

### ISSUE THREAD

**Issue by Razunter** [syntaxfm/website#769]
1. RSS file is ~6mb. That's too much.
2. All RSS links lead to the frontpage, not to the appropriate episodes.

**Comment by stolinski** [comment]
1. This is a tough one. After doing some research here, pagination isn't very standard in RSS and the only other option it to have less data in there. I think we'll probably have to take a look at just how much of the show notes we need in our feed because I'm sure that's the big problem.
2. Will be fixed.

**Comment by wesbos** [comment]
Yeah the RSS feeds of all podcasts are huge. I know podcast providers move around terrabytes of xml every day.

**Comment by stolinski** [comment]
The feed in question is the feed for podcast apps. I have made a 2nd RSS feed that is more consumable for normal users. https://beta.syntax.fm/rss

**Comment by map7** [comment]
Don't know if this is related, but the RSS link on your website doesn't work in my podcast software and I had to use the beta syntax RSS feed instead.
