### ISSUE TITLE
Summary + Tagging

### ISSUE THREAD

**Issue by wesbos** [syntaxfm/website#959]
Once the transcripts are implemented, I'd like to feed that into Open AI and get quick timestamp level transcripts of the entire show, as well as a list of tags for the show

**Comment by stolinski** [comment]
I started this prompt. it's been working decently, but can be tuned more.
`Please follow these rules: I'm going to give you show notes for a podcast. I'd like you to return a typescript array of strings with tags that properly represent the content. Please omit headings like Sick Picks and Show notes. Keep it to the 6 most important tags, tags should be more specific. ie React instead of React Components, in general tags should just be one or two words at most and defaulting to one word unless the 2nd is needed for proper context. Only output the array nothing else`

**Comment by wesbos** [comment]
This has been implemented
